# .air.toml

[build]
# Command to build the project
cmd = "go build -o ./tmp/main cmd/nebula_backend/main.go"
# Binary to run after build
bin = "tmp/main"
# Watch these directories for changes
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "migrations"]

[log]
level = "debug"